bar:
   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  
  # Position Controllers ---------------------------------------
  j_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shaft
    pid: {p: 0.3, i: 0.3, d: 0.075}

 
